# Numpy arrays
Наиболее распространённая структура из numpy это `ndarray`. Для начала посмотрим, как их создавать
## Создание одномерных массиов из главных iterable типов

Для начала, `ndarray` может создаваться из встроенных `list` или `tuple` при помощи функции `np.array(iterable)`:

In [1]:
import numpy as np  # np - community accepted abbrevation

some_list = [4, 8, 15, 16, 23, 42]
some_tuple = (np.sqrt(2), np.exp(1), np.pi)

from_list = np.array(some_list)
from_tuple = np.array(some_tuple)

print(f"from list: \n{from_list}, shape: {from_list.shape}, dtype: {from_list.dtype}")
print(f"\nfrom tuple: \n{from_tuple}, shape: {from_tuple.shape}, dtype: {from_tuple.dtype}")

from list: 
[ 4  8 15 16 23 42], shape: (6,), dtype: int32

from tuple: 
[1.41421356 2.71828183 3.14159265], shape: (3,), dtype: float64


Однако, другие `iterable` типы не подходят. Взгляните на следующий пример и обратите внимание на shape:

In [2]:
some_set = set('an assassin sins')
some_string = 'The quick brown fox jumps over the lazy dog'

from_set = np.array(some_set)
from_string = np.array(some_string)

print(f"from set: \n{from_set}, shape: {from_set.shape}, dtype: {from_set.dtype}")
print(f"\nfrom string: \n{from_string}, shape: {from_string.shape}, dtype: {from_string.dtype}")

from set: 
{'n', 'i', ' ', 's', 'a'}, shape: (), dtype: object

from string: 
The quick brown fox jumps over the lazy dog, shape: (), dtype: <U43


Но если вам ну очень хочется сделать `ndarray` из `set` или `string`, вы можете обернуть их в `list`

In [3]:
from_listed_set = np.array(list(some_set))
from_listed_string = np.array(list(some_string))

print(f"from list(set): \n{from_listed_set}, shape: {from_listed_set.shape}, dtype: {from_listed_set.dtype}")
print(f"\nfrom list(string): \n{from_listed_string}, shape: {from_listed_string.shape}, dtype: {from_listed_string.dtype}")

from list(set): 
['n' 'i' ' ' 's' 'a'], shape: (5,), dtype: <U1

from list(string): 
['T' 'h' 'e' ' ' 'q' 'u' 'i' 'c' 'k' ' ' 'b' 'r' 'o' 'w' 'n' ' ' 'f' 'o'
 'x' ' ' 'j' 'u' 'm' 'p' 's' ' ' 'o' 'v' 'e' 'r' ' ' 't' 'h' 'e' ' ' 'l'
 'a' 'z' 'y' ' ' 'd' 'o' 'g'], shape: (43,), dtype: <U1


Тип данных `<U1` означает "unicode строка длиной 1 или меньше". Тип данных всегда изменяется **явно** и **приводит к созданию нового объекта**.
Посмотрите пример:

In [4]:
some_string = 'The quick brown fox jumps over the lazy dog'
words_list = some_string.lower().split(' ')
from_words_list = np.array(words_list)

print(f"from words list: \n{from_words_list}, shape: {from_words_list.shape}, dtype: {from_words_list.dtype}, id: {id(from_words_list)}")

print('\nЗаменим fox на elephant:')
from_words_list[3] = 'elephant'
print(f"from words list: \n{from_words_list}, shape: {from_words_list.shape}, dtype: {from_words_list.dtype}, id: {id(from_words_list)}")
print('Слон стал "элефом", но id не изменился')

print('\nСменим тип данных и заменим eleph на elephant:')
from_words_list = from_words_list.astype('<U10')
from_words_list[3] = 'elephant'
print(f"from words list: \n{from_words_list}, shape: {from_words_list.shape}, dtype: {from_words_list.dtype}, id: {id(from_words_list)}")

from words list: 
['the' 'quick' 'brown' 'fox' 'jumps' 'over' 'the' 'lazy' 'dog'], shape: (9,), dtype: <U5, id: 1988783091120

Заменим fox на elephant:
from words list: 
['the' 'quick' 'brown' 'eleph' 'jumps' 'over' 'the' 'lazy' 'dog'], shape: (9,), dtype: <U5, id: 1988783091120
Слон стал "элефом", но id не изменился

Сменим тип данных и заменим eleph на elephant:
from words list: 
['the' 'quick' 'brown' 'elephant' 'jumps' 'over' 'the' 'lazy' 'dog'], shape: (9,), dtype: <U10, id: 1988783277712


Очевидно, `ndarray` не очень для работы со строками. Однако с числами он бесподобен.

## Создание n-мерных массивов из основных iterable типов:
n-мерные массивы `np.ndarray` могут быть получены оборачиванием в np.array() `list`, содержащий внутри себя другие `list`. Попробуем создать двухмерный массив (словом, матрицу):

In [5]:
lists_in_list = [[1, 2, 3], [4, 5, 6]]
matrix = np.array(lists_in_list)
print(f"From lists in list: \n{matrix}, shape: {matrix.shape}, len: {len(matrix)}")

From lists in list: 
[[1 2 3]
 [4 5 6]], shape: (2, 3), len: 2


Внимательно посмотрите на вывод предыдущего примера. Будьте осторожны при использовании функции `len()` с типом данных `ndarray`. Она вернёт длину первого измерения, а не количество элементов. Для получения количества элементов используется атрибут `ndarray.size`

ndarray с б**о**льшим количеством измерений получается путём увеличения уровня вложенности: 

In [6]:
lists_in_lists_in_list = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]
three_d_array = np.array(lists_in_lists_in_list)
print(f"From lists in list: \n{three_d_array}, shape: {three_d_array.shape}, len: {len(three_d_array)}, size: {three_d_array.size}")

From lists in list: 
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]], shape: (2, 3, 3), len: 2, size: 18


Разумеется, вложенные `list` должны быть согласованны в смысле числа элементов:

In [7]:
incompatible_lists_in_list = [[1, 2, 3], [4, 5], [6, 7, 8]]
from_incompatible_lists = np.array(incompatible_lists_in_list)
print(f"From incompatible lists: \n{from_incompatible_lists}, shape: {from_incompatible_lists.shape}, dtype: {from_incompatible_lists.dtype}")

From incompatible lists: 
[list([1, 2, 3]) list([4, 5]) list([6, 7, 8])], shape: (3,), dtype: object


C:\Users\gr682_ggi\AppData\Local\Temp\ipykernel_8040\3402212028.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  from_incompatible_lists = np.array(incompatible_lists_in_list)


## Процедуры создания новых массивов
### Инициализация raw-массива
Можно инициализировать массив без значений. При инициализации numpy-массива без значений создаётся указатель на свободную область в памяти. Если посмотреть содержимаое массива, то можно увидеть что оказалось в той области памяти, а оказаться там может всё, что угодно. Попробуйте поменять shape и посмотреть как меняется содержимое

In [8]:
shape = (4, 4)
new_array = np.ndarray(shape=shape)
print(f"new array: \n{new_array}, dtype: {new_array.dtype}")

new array: 
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.22388739e-307]
 [1.02359848e-306 8.34441742e-308 1.78022342e-306 6.23058028e-307]
 [9.79107872e-307 6.89807188e-307 7.56594375e-307 6.23060065e-307]
 [1.78021527e-306 8.34454050e-308 1.11261027e-306 2.04712907e-306]], dtype: float64


### Заполненные массивы
Во многих случаях могут понадобиться массивы, которые состоят из один единиц или нулей. Такие массивы гененрируются функциями `np.zeros(shape=required_shape)` и `np.ones(shape=required_shape)` соответственно. `shape` может быть целым числом (для `1D-array`) или `tuple` целых чисел для `ndarray`.

In [9]:
zeros_1d = np.zeros(10)
print(f"zeros_1d: \n{zeros_1d}, shape: {zeros_1d.shape}, dtype: {zeros_1d.dtype}")
ones_2d = np.ones((3, 3))
print(f"ones_2d: \n{ones_2d}, shape: {ones_2d.shape}, dtype: {ones_2d.dtype}")

zeros_1d: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape: (10,), dtype: float64
ones_2d: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape: (3, 3), dtype: float64


Тип данных для значений таких массивов может быть задан явно через параметр `dtype`:

In [11]:
uint_ones = np.ones(7, dtype=np.uint8)
print(f"uint zeros: \n{uint_ones}, shape: {uint_ones.shape}, dtype: {uint_ones.dtype}")

uint zeros: 
[1 1 1 1 1 1 1], shape: (7,), dtype: uint8


Давайте выполним несколько операций для того, чтобы убедиться, что у нас действительно `uint8`:

In [10]:
uint_ones = np.ones(7, dtype=np.uint8)
uint_ones[0] = uint_ones[0]  # Left first one alone
uint_ones[1] -= 0.2 
uint_ones[2] += 0.9  
uint_ones[3] += 1.1
uint_ones[4] += 300
uint_ones[5] -= 10
uint_ones[6] *= -1

### Равномерно заполненные массивы
В качестве первого типа равнозаполненных массиов рассмотрим функцию `np.arange()`. Она работает по аналогии со стандартной `range()`, но возвращает `ndarray` и позволяет использовать не только целочисленные значения шага.

In [12]:
print('# Если передадим единственный аргумент N, arange вернёт целые числа из интервала [0, N). Как и обычный range()')
print(f'np.arange(10) \n{np.arange(10)}')

print('\n# Для двух аргументов M и N, arange вернёт целые из интервала [M, N). Снова по аналогии с range():')
print(f'np.arange(5, 10) \n{np.arange(5, 10)}')

print('\n# Третий аргумент указывает шаг внутри интервала [M, N):')
print(f'np.arange(5, 10, 0.5) \n{np.arange(5, 10, 0.5)}')
print(f'\nnp.arange(5, 10, 2) \n{np.arange(5, 10, 2)}')
print(f'\nnp.arange(5, 10, 10) \n{np.arange(5, 10, 10)}')

# Если передадим единственный аргумент N, arange вернёт целые числа из интервала [0, N). Как и обычный range()
np.arange(10) 
[0 1 2 3 4 5 6 7 8 9]

# Для двух аргументов M и N, arange вернёт целые из интервала [M, N). Снова по аналогии с range():
np.arange(5, 10) 
[5 6 7 8 9]

# Третий аргумент указывает шаг внутри интервала [M, N):
np.arange(5, 10, 0.5) 
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

np.arange(5, 10, 2) 
[5 7 9]

np.arange(5, 10, 10) 
[5]


В иных ситуациях удобнее использовать не фиксированный шаг, а фиксированное количество равноудалённых точек из интервала. Для такой задачи используется функция `np.linspace()`.

In [13]:
print('# В отличии от arange, linspace ожидает минимум два аргумента: start и stop. А ещё linspace обычно включает в себя правую границу интервала:')
print(f'np.linspace(0, 10): \n{np.linspace(0, 10)}, shape: {np.linspace(0, 10).shape}')

print('\n# По умолчанию linspace разбиавает интервал на 50 точек. Однако количество точек можно задать третьим аргументом:')
print(f'np.linspace(0, 10, 21): \n{np.linspace(0, 10, 21)}, shape: {np.linspace(0, 10, 21).shape}')

print('\n#  Если же задача не требует включения правой границы интервала, передаётся аргумент endpoint=False')
print(f'np.linspace(0, 10, 20, endpoint=False): \n{np.linspace(0, 10, 20, endpoint=False)}, shape: {np.linspace(0, 10, 20, endpoint=False).shape}')

# В отличии от arange, linspace ожидает минимум два аргумента: start и stop. А ещё linspace обычно включает в себя правую границу интервала:
np.linspace(0, 10): 
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ], shape: (50,)

# По умолчанию linspace разбиавает интервал на 50 точек. Однако количество точек можно задать третьим аргументом:
np.linspace(0, 10, 21): 
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7

## Создание массивов случайных чисел
Рассмотрим три основные фукнции создания массивов, заполненных случайными числами. Начнём с функции `np.random.randn()`. Она генерирует число, распределённое по нормальному закону с математическим ожиданием = 0 и дисперсией = 1

In [14]:
print("# Без указания аргументов возвращает единственное число базового типа float")
print(f'np.random.randn(): {np.random.randn()}, type: {type(np.random.randn())}')

print("\n# Чтобы создать ndarray в качестве аргументов передаётся его shape")
print(f'np.random.randn(1, 2, 3, 4): \n{np.random.randn(1, 2, 3, 4)}, type: {type(np.random.randn(1, 2, 3, 4))}, shape: {np.random.randn(1, 2, 3, 4).shape}')

print("\n# То же самое, только через кортеж:")
shape = (4, 3, 2)
print(f'np.random.randn(*shape): \n{np.random.randn(*shape)}, type: {type(np.random.randn(*shape))}, shape: {np.random.randn(*shape).shape}')

# Без указания аргументов возвращает единственное число базового типа float
np.random.randn(): 0.9674077085820182, type: <class 'float'>

# Чтобы создать ndarray в качестве аргументов передаётся его shape
np.random.randn(1, 2, 3, 4): 
[[[[ 0.87743586  0.64112689 -0.68373593 -0.82787752]
   [ 0.30667839  0.65105122 -0.45826112 -0.87295888]
   [ 0.99428474  0.41469059  0.62440644  0.13977799]]

  [[ 0.56499438 -1.98787304  0.43763197 -0.17790469]
   [-0.05170528  1.49395709 -0.81575985  0.57820279]
   [ 0.42103592  0.1844842  -0.50968     0.7511873 ]]]], type: <class 'numpy.ndarray'>, shape: (1, 2, 3, 4)

# То же самое, только через кортеж:
np.random.randn(*shape): 
[[[-1.03250563  0.05885367]
  [ 1.7567343   0.26082569]
  [ 0.71200134  0.84815414]]

 [[ 0.62914271  0.16752895]
  [ 1.64863305 -0.76674934]
  [-0.1629912  -0.66617969]]

 [[ 0.08271661 -0.9840397 ]
  [ 1.56868428 -0.17532278]
  [ 0.02392696 -1.25558974]]

 [[-0.71543782  1.20129121]
  [-1.03799418  0.17774406]
  [ 2.9105037

### np.rand.rand()
Работает точно так же, как и `np.random.randn()`, только генерирует числа по равномерному закону распределения

In [15]:
print(f'np.random.rand(): {np.random.rand()}, type: {type(np.random.rand())}')


shape = (2, 3, 4)
print(f'\nnp.random.rand(*shape): \n{np.random.rand(*shape)}, type: {type(np.random.rand(*shape))}, shape: {np.random.rand(*shape).shape}')

np.random.rand(): 0.07794029029661242, type: <class 'float'>

np.random.rand(*shape): 
[[[0.46358098 0.49228981 0.95181793 0.97221682]
  [0.10919843 0.31814402 0.83748991 0.429213  ]
  [0.33763274 0.83188907 0.80833906 0.21369516]]

 [[0.79804046 0.01734892 0.45986784 0.92847836]
  [0.03391777 0.66388175 0.55607866 0.23003651]
  [0.38771649 0.43299606 0.74759785 0.76159552]]], type: <class 'numpy.ndarray'>, shape: (2, 3, 4)


### np.random.randint()

In [16]:
print("# Если randint вызывается с единственным аргументом N, функция вернёт единственный базовый int из области [0, N)")
print(f'np.random.randint(100): {np.random.randint(100)}, type: {type(np.random.randint(100))}')

print("\n# Если передать два аргумента M и N, функция вернёт единственный базовый int из области [M, N)")
print(f'np.random.randint(90, 100): {np.random.randint(100)}, type: {type(np.random.randint(100))}')


print('\n# А вот если третьим аргументом передать размер, то получим ndarray:')
print(f'np.random.randint(90, 100, 10): \n{np.random.randint(90, 100, 10)}, type: {type(np.random.randint(90, 100, 10))}')
print('\n# Однако, в отличии от предыдущих двух функций, здесь под размер отведён единственный аргумент. Поэтому, многомерный массив получаем передачай tuple:')
print(f'np.random.randint(0, 10, (3, 3)): \n{np.random.randint(0, 10, (3, 3))}')

print(f'\n# Необязательно передавать три значения чтобы задать размер. Аргумент size можно указать явно.')
print('# Такая запись эквивалентна np.random.randint(0, 100, 10)')
print(f'np.random.randint(100, size=10): \n{np.random.randint(100, size=10)}, type: {type(np.random.randint(100, size=10))}')


# Если randint вызывается с единственным аргументом N, функция вернёт единственный базовый int из области [0, N)
np.random.randint(100): 49, type: <class 'int'>

# Если передать два аргумента M и N, функция вернёт единственный базовый int из области [M, N)
np.random.randint(90, 100): 78, type: <class 'int'>

# А вот если третьим аргументом передать размер, то получим ndarray:
np.random.randint(90, 100, 10): 
[96 91 99 93 93 98 96 91 92 90], type: <class 'numpy.ndarray'>

# Однако, в отличии от предыдущих двух функций, здесь под размер отведён единственный аргумент. Поэтому, многомерный массив получаем передачай tuple:
np.random.randint(0, 10, (3, 3)): 
[[1 2 7]
 [5 9 4]
 [5 9 3]]

# Необязательно передавать три значения чтобы задать размер. Аргумент size можно указать явно.
# Такая запись эквивалентна np.random.randint(0, 100, 10)
np.random.randint(100, size=10): 
[48 44  9 16 85 12 33 43 57  4], type: <class 'numpy.ndarray'>
